### PR TITLE
Add key shortcut to clear output panel

### LINKED ISSUE #12: Is it possible to clear Reveal output pane?
Thank you for this software!

Is there any way to clear Reveal output pane when needed?

### PR DESCRIPTION
**Pull request by nenadalm**
fixes #12 

Hi. Thanks for the awesome app. I am trying to write log viewer for postgres (https://github.com/nenadalm/postgresql-log-viewer#postgresql-log-viewer) and currently I am investigating if it is possible to use some existing data browser as ui.

It would be nice if I could clear queries so far (say before making a http request that produces some queries) and see all queries that happened during that request. It seems that code in this pr does the trick.

### CODE REVIEW

**Comment by vlaaad** [comment]
Hi @nenadalm! 

Thanks for your interest, it's a simple and focused contribution 👍 

Unfortunately, as minor as it seems, I decided not to accept it today because I don't like the idea of growing the amount of shortcuts that don't have any discoverability. `Ctrl+F` as search and `Ctrl+C` as copy might be ubiquitous, but `Ctrl+D` as clearing is not. I am planning to add a way to add contextual actions on views that are discoverable and extensible, and clearing the output absolutely will be there, but that will probably cause the whole keyboard event handling to change.

**Comment by nenadalm** [comment]
Thanks. That would be great.

Portal (another data browser), has such commands: https://github.com/djblue/portal/blob/8227595ee3c32e3f36c38d5e6c6e3cf19198f4be/src/portal/ui/commands.cljs#L305 which can be shown by opening command menu using ctrl+shift+p, which works like the one in vscode (https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

Also I just noticed that Portal is using ctrl+l to clear the output (I was using button to do that as I didn't know about the shortcut), so maybe should there be shortcut in reveal, it could be also ctrl+l instead of ctrl+d as in this pr.

I suppose that contextual actions in reveal will work similar way as commands in portal/vscode?

**Comment by vlaaad** [comment]
I haven't decided yet how they will look like, could be like in vscode/portal :)

Thank you for understanding and patience!

**Comment by svdo** [comment]
Just my 2 cents:

- This is the feature that I'm missing most, so I can't wait for the "clear" to become available
- I vote for using the same keyboard shortcut as terminals and vscode terminals: command-K (not sure what that should be on Windows...)

**Comment by vlaaad** [comment]
I understand. I'll try to release something soon, probably bound to Ctrl+L or Ctrl+K.

**Comment by vlaaad** [comment]
Released `1.1.171` that adds <kbd>Ctrl L</lbd> as a shortcut for clearing the output panel. It uses <kbd>Ctrl</kbd> (instead of `⌘`) on Mac too for consistency.

**Comment by svdo** [comment]
Super duper! Very happy with that feature :)

**Pull request closed without merging**
